apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-processor
  template:
    metadata:
      labels:
        app: text-processor
    spec:
      containers:
      - name: text-processor
        image: my_docker_image:latest
        imagePullPolicy: Never
      